// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: mesh.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SynchronousRelayService_ProposeEvents_FullMethodName = "/monotonic.SynchronousRelayService/ProposeEvents"
	SynchronousRelayService_PollEvents_FullMethodName    = "/monotonic.SynchronousRelayService/PollEvents"
)

// SynchronousRelayServiceClient is the client API for SynchronousRelayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SynchronousRelayService is a service representing a synchronous relay connection between nodes
type SynchronousRelayServiceClient interface {
	// ProposeEvents is for proposing an event batch
	ProposeEvents(ctx context.Context, in *ProposedEventsBatch, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// PollEvents polls event stream from the node based on provided event filter
	PollEvents(ctx context.Context, in *PollEventsRequest, opts ...grpc.CallOption) (*EventStream, error)
}

type synchronousRelayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSynchronousRelayServiceClient(cc grpc.ClientConnInterface) SynchronousRelayServiceClient {
	return &synchronousRelayServiceClient{cc}
}

func (c *synchronousRelayServiceClient) ProposeEvents(ctx context.Context, in *ProposedEventsBatch, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SynchronousRelayService_ProposeEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *synchronousRelayServiceClient) PollEvents(ctx context.Context, in *PollEventsRequest, opts ...grpc.CallOption) (*EventStream, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventStream)
	err := c.cc.Invoke(ctx, SynchronousRelayService_PollEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SynchronousRelayServiceServer is the server API for SynchronousRelayService service.
// All implementations must embed UnimplementedSynchronousRelayServiceServer
// for forward compatibility.
//
// SynchronousRelayService is a service representing a synchronous relay connection between nodes
type SynchronousRelayServiceServer interface {
	// ProposeEvents is for proposing an event batch
	ProposeEvents(context.Context, *ProposedEventsBatch) (*emptypb.Empty, error)
	// PollEvents polls event stream from the node based on provided event filter
	PollEvents(context.Context, *PollEventsRequest) (*EventStream, error)
	mustEmbedUnimplementedSynchronousRelayServiceServer()
}

// UnimplementedSynchronousRelayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSynchronousRelayServiceServer struct{}

func (UnimplementedSynchronousRelayServiceServer) ProposeEvents(context.Context, *ProposedEventsBatch) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeEvents not implemented")
}
func (UnimplementedSynchronousRelayServiceServer) PollEvents(context.Context, *PollEventsRequest) (*EventStream, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PollEvents not implemented")
}
func (UnimplementedSynchronousRelayServiceServer) mustEmbedUnimplementedSynchronousRelayServiceServer() {
}
func (UnimplementedSynchronousRelayServiceServer) testEmbeddedByValue() {}

// UnsafeSynchronousRelayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SynchronousRelayServiceServer will
// result in compilation errors.
type UnsafeSynchronousRelayServiceServer interface {
	mustEmbedUnimplementedSynchronousRelayServiceServer()
}

func RegisterSynchronousRelayServiceServer(s grpc.ServiceRegistrar, srv SynchronousRelayServiceServer) {
	// If the following call pancis, it indicates UnimplementedSynchronousRelayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SynchronousRelayService_ServiceDesc, srv)
}

func _SynchronousRelayService_ProposeEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposedEventsBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynchronousRelayServiceServer).ProposeEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SynchronousRelayService_ProposeEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynchronousRelayServiceServer).ProposeEvents(ctx, req.(*ProposedEventsBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _SynchronousRelayService_PollEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynchronousRelayServiceServer).PollEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SynchronousRelayService_PollEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynchronousRelayServiceServer).PollEvents(ctx, req.(*PollEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SynchronousRelayService_ServiceDesc is the grpc.ServiceDesc for SynchronousRelayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SynchronousRelayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monotonic.SynchronousRelayService",
	HandlerType: (*SynchronousRelayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProposeEvents",
			Handler:    _SynchronousRelayService_ProposeEvents_Handler,
		},
		{
			MethodName: "PollEvents",
			Handler:    _SynchronousRelayService_PollEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mesh.proto",
}
